development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: asflash
  pool: 5
  username: adelaida
  password: Jgus83igy

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: asflash_test
  pool: 5
  username: adelaida
  password: Jgus83igy

production:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: asflash
  pool: 5
  username: adelaida
  password: Jgus83igy