development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: Tabularasa
  pool: 5
  username: user
  password: hello

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: Tabularasa_test
  pool: 5
  username: user
  password: hello

production:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: Tabularasa
  pool: 5
  username: user
  password: hello
